# Generated by Django 2.0.4 on 2018-04-18 19:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyname', models.CharField(max_length=50)),
                ('forenames', models.TextField(blank=True)),
                ('affiliation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('asid', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperReco.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Coauthorship',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('aid1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paperReco.Author')),
                ('aid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='paperReco.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('doi', models.CharField(max_length=30, unique=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None)),
                ('date', models.CharField(max_length=20)),
                ('tokens', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='authorship',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paperReco.Paper'),
        ),
    ]
