# Generated by Django 2.0.4 on 2018-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperReco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='keyname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
