# Generated by Django 2.0.4 on 2018-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperReco', '0002_auto_20180420_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='keyname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('keyname', 'forenames', 'affiliation')},
        ),
    ]
