# Generated by Django 2.0.4 on 2018-04-24 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paperReco', '0003_auto_20180420_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='date_mod',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
