# Generated by Django 2.0.4 on 2018-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperReco', '0004_paper_date_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='date_mod',
        ),
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(),
        ),
    ]
